apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-linux-update-operator
  namespace: reboot-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: container-linux-update-operator
  template:
    metadata:
      labels:
        name: container-linux-update-operator
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
        - name: update-operator
          image: quay.io/coreos/container-linux-update-operator:v0.7.0
          command:
            - "/bin/update-operator"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 20m
              memory: 40Mi

